# Generated by Django 4.2.1 on 2023-05-31 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weight", models.FloatField()),
                ("breakfast", models.TextField(max_length=100)),
                ("lunch", models.TextField(max_length=100)),
                ("dinner", models.TextField(max_length=100)),
                ("other_meals", models.TextField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiaryPhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("photo", models.ImageField(upload_to="diary_photos")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diary.diary"
                    ),
                ),
            ],
        ),
    ]
